version: '3.1'

services:

  chat-frontend:
    depends_on:
      - chat-backend
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    environment:
      REACT_APP_SOCKET_URL: http://chat-backend:3500

  chat-backend:
    build:
      context: ./backend
    ports:
      - "3500:3500"
    environment:
      NODE_ENV: development
      APP_PORT: 3500
